version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
